name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install System Dependencies
        run: |
          sudo apt update && sudo apt install -y \
          python3-pip build-essential git unzip zip \
          default-jdk libffi-dev libssl-dev \
          libjpeg-dev zlib1g-dev \
          libsqlite3-dev libgles2-mesa-dev \
          libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
          libgstreamer-plugins-good1.0-dev

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip setuptools wheel
          pip install cython buildozer

      - name: Install Android SDK & AIDL
        run: |
          sudo apt install -y android-sdk adb
          yes | sdkmanager --licenses
          sdkmanager "platform-tools" "platforms;android-31" "build-tools;31.0.0" "cmdline-tools;latest" "ndk;23.1.7779620"

      - name: Initialize Buildozer (If Not Exists)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Modify Buildozer Spec File
        run: |
          sed -i 's/^source.include_exts =.*/source.include_exts = py,png,jpg,kv,atlas/' buildozer.spec
          sed -i 's/^requirements =.*/requirements = python3,flask,kivy,kivy-garden/' buildozer.spec
          sed -i 's/^package.domain =.*/package.domain = org.firstbytebox/' buildozer.spec
          sed -i 's/^package.name =.*/package.name = FirstByteBox/' buildozer.spec
          sed -i 's/^package.version =.*/package.version = 1.0.0/' buildozer.spec

      - name: Build APK
        run: buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MyFlaskApp-APK
          path: bin/*.apk
