name: Build Flask App with Buildozer

on:
  push:
    branches:
      - main  # Change this to your default branch
  pull_request:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          python3-dev \
          python3-pip \
          python3-setuptools \
          git \
          unzip \
          openjdk-8-jdk \
          libgl1-mesa-dev \
          libglu1-mesa-dev \
          libxi-dev \
          libxmu-dev \
          libx11-dev \
          libxrandr-dev \
          libxinerama-dev \
          libxcursor-dev \
          libfreetype6-dev \
          libpng-dev \
          libjpeg-dev \
          zlib1g-dev \
          libssl-dev \
          libffi-dev \
          libsqlite3-dev \
          libgstreamer1.0-dev \
          libgstreamer-plugins-base1.0-dev

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer

    - name: Build the app in debug mode
      run: |
        cd your_flask_project_directory  # Change this to your Flask project directory
        buildozer -v android debug  # Build the app in debug mode

    - name: Upload the APK
      uses: actions/upload-artifact@v2
      with:
        name: my-flask-app-debug
        path: your_flask_project_directory/bin/*.apk  # Change this to your APK output path
