name: Build BeeWare Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install briefcase  # Install BeeWare's Briefcase

    - name: Build for macOS
      run: |
        briefcase build macOS

    - name: Build for Android
      run: |
        briefcase build android

    - name: Upload macOS Build
      uses: actions/upload-artifact@v4
      with:
        name: macOS Build
        path: ./macOS/build/*  # Adjust the path to your macOS build output

    - name: Upload Android Build
      uses: actions/upload-artifact@v4
      with:
        name: Android Build
        path: ./android/build/*  # Adjust the path to your Android build output