name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-dev \
              build-essential git openjdk-11-jdk unzip zip \
              libncurses5-dev libstdc++6 libffi-dev libssl-dev \
              libsqlite3-dev libgdbm-dev libbz2-dev liblzma-dev \
              zlib1g-dev libreadline-dev tk-dev
          pip install buildozer cython  # Install Cython along with Buildozer

      - name: Install Android SDK Command-Line Tools
        run: |
          # Download the command-line tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/android-sdk
          rm commandlinetools-linux-7583922_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest

      - name: Set up Android SDK
        run: |
          echo "export ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH" >> $GITHUB_ENV
          echo "export PATH=$ANDROID_HOME/tools/bin:$PATH" >> $GITHUB_ENV

      - name: Install Android SDK Packages
        run: |
          yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses
          sdkmanager --sdk_root=$ANDROID_HOME "platform-tools" "platforms;android-30" "build-tools;30.0.3"  # Adjust the API level as needed

      - name: Initialize Buildozer (if not exists)
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init  # This creates the buildozer.spec file if it doesn't exist
          else
            echo "buildozer.spec already exists, skipping initialization."
          fi

      - name: Build Android APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: android-debug-apk
          path: bin/*.apk  # Adjust the path if your APK is located elsewhere
