name: Build Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt  # Install other dependencies if you have a requirements file

    - name: Build executable
      run: |
        pyinstaller --onefile main.py  # Replace 'your_script.py' with your main Python file

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: main
        path: dist/main  # Adjust the path to your executable
